name: urban-test
dependencies:
-backports-abc==0.5
-backports.ssl-match-hostname==3.5.0.1
-backports_abc==0.5
-branca==0.2.0
	-certifi==2017.4.17
	-click==6.7
	-click-plugins==1.0.3
	-cligj==0.4.0
	-curl==7.52.1
	-cycler==0.10.0
	-dbus==1.10.10
	-decorator==4.0.11
	-descartes==1.1.0
	-enum34==1.1.6
	-expat==2.1.0
	-fiona==1.7.6
	-folium==0.3.0
	-fontconfig==2.12.1
	-freetype==2.7
	-freexl==1.0.2
	-functools32==3.2.3.2
	-gdal==2.1.3
	-geopandas==0.2.1
	-geopy==1.11.0
	-geos==3.5.1
	-gettext==0.19.7
	-giflib==5.1.4
	-glib==2.51.4
	-gst-plugins-base==1.8.0
	-gstreamer==1.8.0
	-hdf4==4.2.12
	-hdf5==1.8.17
	-icu==58.1
	-jinja2==2.9.6
	-jpeg==9b
	-json-c==0.12
	-kealib==1.4.7
	-krb5==1.14.2
	-libdap4==3.18.3
	-libffi==3.2.1
	-libgcc==5.2.0
	-libgfortran==3.0.0
	-libiconv==1.14
	-libnetcdf==4.4.1.1
	-libpng==1.6.28
	-libpq==9.5.4
	-libspatialindex==1.8.5
	-libspatialite==4.3.0a
	-libtiff==4.0.6
	-libxcb==1.12
	-libxml2==2.9.4
	-markupsafe==0.23
	-matplotlib==2.0.2
	-mkl==2017.0.1
	-munch==2.1.1
	-ncurses==5.9
	-networkx==1.11
	-numpy==1.12.1
	-openjpeg==2.1.2
	-openssl==1.0.2k
	-osmnx==0.5.1
	-pandas==0.20.1
	-pcre==8.39
	-pip==9.0.1
	-proj4==4.9.3
	-psycopg2==2.7.1
	-pyparsing==2.2.0
	-pyproj==1.9.5.1
	-pyqt==5.6.0
	-pysal==1.13.0
	-python==2.7.13
	-python-dateutil==2.6.0
	-pytz==2017.2
	-qt==5.6.2
	-readline==6.2
	-requests==2.14.2
	-rtree==0.8.3
	-scipy==0.19.0
	-setuptools==27.2.0
	-shapely==1.5.17
	-singledispatch==3.4.0.3
	-sip==4.18
	-six==1.10.0
	-sqlalchemy==1.1.9
	-sqlite==3.13.0
	-ssl_match_hostname==3.5.0.1
	-subprocess32==3.2.7
	-tk==8.5.18
	-tornado==4.5.1
	-util-linux==2.21
	-vincent==0.4.4
	-wheel==0.29.0
	-wxpython==3.0.0.0
	-wxpython-common==3.0.0.0
	-xerces-c==3.1.4
	-xorg-libxau==1.0.8
	-xorg-libxdmcp==1.1.2
	-xz==5.2.2
	-zlib==1.2.8
